Updates

diff --git a/home/private_dot_local/bin/executable_git-alias b/home/private_dot_local/bin/executable_git-alias
--- a/home/private_dot_local/bin/executable_git-alias
+++ b/home/private_dot_local/bin/executable_git-alias
@@ -5,26 +5,26 @@ unset -v GREP_OPTIONS
 
 # make a temporary file
 git_extra_mktemp() {
-    mktemp -t "$(basename "$0")".XXXXXXX
+  mktemp -t "$(basename "$0")".XXXXXXX
 }
 
 git_extra_default_branch() {
-    local extras_default_branch init_default_branch
-    extras_default_branch=$(git config --get git-extras.default-branch)
-    init_default_branch=$(git config --get init.defaultBranch)
-    if [ -n "$extras_default_branch" ]; then
-        echo "$extras_default_branch"
-    elif [ -n "$init_default_branch" ]; then
-        echo "$init_default_branch"
-    else
-        echo "main"
-    fi
+  local extras_default_branch init_default_branch
+  extras_default_branch=$(git config --get git-extras.default-branch)
+  init_default_branch=$(git config --get init.defaultBranch)
+  if [ -n "$extras_default_branch" ]; then
+    echo "$extras_default_branch"
+  elif [ -n "$init_default_branch" ]; then
+    echo "$init_default_branch"
+  else
+    echo "main"
+  fi
 }
 
 options=""
 
 usage() {
-cat <<HERE
+  cat <<HERE
 usage: git alias [options]                          # list all aliases
    or: git alias [options] <search-pattern>         # show aliases matching pattern
    or: git alias [options] <alias-name> <command>   # alias a command
@@ -36,31 +36,31 @@ HERE
 }
 
 if [[ "$1" == "--local" || "$1" == "--global" ]]; then
-    options=$1
-    shift
+  options=$1
+  shift
 fi
 
 case $# in
-  0)
-      if [[ -z "$options" ]]; then
-        git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
-      else
-        git config "$options" --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
-      fi
-      ;;
-  1)
-      if [[ -z "$options" ]]; then
-        git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort | grep -e "$1"
-      else
-        git config "$options" --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort | grep -e "$1"
-      fi
-      ;;
-  2)
-      if [[ -z "$options" ]]; then
-        git config alias."$1" "$2"
-      else
-        git config "$options" alias."$1" "$2"
-      fi
-      ;;
-  *) >&2 echo "error: too many arguments." && usage && exit 1 ;;
+0)
+  if [[ -z "$options" ]]; then
+    git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
+  else
+    git config "$options" --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
+  fi
+  ;;
+1)
+  if [[ -z "$options" ]]; then
+    git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort | grep -e "$1"
+  else
+    git config "$options" --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort | grep -e "$1"
+  fi
+  ;;
+2)
+  if [[ -z "$options" ]]; then
+    git config alias."$1" "$2"
+  else
+    git config "$options" alias."$1" "$2"
+  fi
+  ;;
+*) >&2 echo "error: too many arguments." && usage && exit 1 ;;
 esac
diff --git a/home/private_dot_local/bin/executable_git-commits-since b/home/private_dot_local/bin/executable_git-commits-since
--- a/home/private_dot_local/bin/executable_git-commits-since
+++ b/home/private_dot_local/bin/executable_git-commits-since
@@ -5,27 +5,27 @@ unset -v GREP_OPTIONS
 
 # make a temporary file
 git_extra_mktemp() {
-    mktemp -t "$(basename "$0")".XXXXXXX
+  mktemp -t "$(basename "$0")".XXXXXXX
 }
 
 git_extra_default_branch() {
-    local extras_default_branch init_default_branch
-    extras_default_branch=$(git config --get git-extras.default-branch)
-    init_default_branch=$(git config --get init.defaultBranch)
-    if [ -n "$extras_default_branch" ]; then
-        echo "$extras_default_branch"
-    elif [ -n "$init_default_branch" ]; then
-        echo "$init_default_branch"
-    else
-        echo "main"
-    fi
+  local extras_default_branch init_default_branch
+  extras_default_branch=$(git config --get git-extras.default-branch)
+  init_default_branch=$(git config --get init.defaultBranch)
+  if [ -n "$extras_default_branch" ]; then
+    echo "$extras_default_branch"
+  elif [ -n "$init_default_branch" ]; then
+    echo "$init_default_branch"
+  else
+    echo "main"
+  fi
 }
 #
 # check whether current directory is inside a git repository
 #
 
 is_git_repo() {
-  git rev-parse --show-toplevel > /dev/null 2>&1
+  git rev-parse --show-toplevel >/dev/null 2>&1
   result=$?
   if test $result != 0; then
     >&2 echo 'Not a git repo!'
@@ -39,7 +39,7 @@ is_git_repo
 #
 
 has_git_commit() {
-  git rev-parse --short HEAD > /dev/null 2>&1
+  git rev-parse --short HEAD >/dev/null 2>&1
   result=$?
   if test $result != 0; then
     >&2 echo 'Not git commit found!'
@@ -53,33 +53,33 @@ REF=""
 SINCE=""
 
 while [[ $# -gt 0 ]]; do
-    case "$1" in
-        -r|--ref)
-            if [[ -z "$2" ]]; then
-                echo "error: option $1 requires an argument" >&2
-                exit 1
-            fi
-            REF="$2"
-            shift
-            shift
-            ;;
-        *)
-            # non-flag args accumulation, e.g. "last " + "week" -> "last week"
-            SINCE="${SINCE:+$SINCE }$1"
-            shift
-            ;;
-    esac
+  case "$1" in
+  -r | --ref)
+    if [[ -z "$2" ]]; then
+      echo "error: option $1 requires an argument" >&2
+      exit 1
+    fi
+    REF="$2"
+    shift
+    shift
+    ;;
+  *)
+    # non-flag args accumulation, e.g. "last " + "week" -> "last week"
+    SINCE="${SINCE:+$SINCE }$1"
+    shift
+    ;;
+  esac
 done
 
 if [[ -n "$REF" && -n "$SINCE" ]]; then
-    echo "error: '--ref <ref>' and '<date>' are mutually exclusive" >&2
-    exit 1
+  echo "error: '--ref <ref>' and '<date>' are mutually exclusive" >&2
+  exit 1
 fi
 
 SINCE="${SINCE:-last week}"
 
 if [[ -n "$REF" ]]; then
-    git log --pretty='%h %an - %s' "$REF..HEAD"
+  git log --pretty='%h %an - %s' "$REF..HEAD"
 else
-    git log --pretty='%h %an - %s' --after="@{$SINCE}"
+  git log --pretty='%h %an - %s' --after="@{$SINCE}"
 fi
diff --git a/home/private_dot_local/bin/executable_git-continue b/home/private_dot_local/bin/executable_git-continue
--- a/home/private_dot_local/bin/executable_git-continue
+++ b/home/private_dot_local/bin/executable_git-continue
@@ -5,27 +5,27 @@ unset -v GREP_OPTIONS
 
 # make a temporary file
 git_extra_mktemp() {
-    mktemp -t "$(basename "$0")".XXXXXXX
+  mktemp -t "$(basename "$0")".XXXXXXX
 }
 
 git_extra_default_branch() {
-    local extras_default_branch init_default_branch
-    extras_default_branch=$(git config --get git-extras.default-branch)
-    init_default_branch=$(git config --get init.defaultBranch)
-    if [ -n "$extras_default_branch" ]; then
-        echo "$extras_default_branch"
-    elif [ -n "$init_default_branch" ]; then
-        echo "$init_default_branch"
-    else
-        echo "main"
-    fi
+  local extras_default_branch init_default_branch
+  extras_default_branch=$(git config --get git-extras.default-branch)
+  init_default_branch=$(git config --get init.defaultBranch)
+  if [ -n "$extras_default_branch" ]; then
+    echo "$extras_default_branch"
+  elif [ -n "$init_default_branch" ]; then
+    echo "$init_default_branch"
+  else
+    echo "main"
+  fi
 }
 #
 # check whether current directory is inside a git repository
 #
 
 is_git_repo() {
-  git rev-parse --show-toplevel > /dev/null 2>&1
+  git rev-parse --show-toplevel >/dev/null 2>&1
   result=$?
   if test $result != 0; then
     >&2 echo 'Not a git repo!'
@@ -42,10 +42,10 @@ gitdir="$(git rev-parse --git-dir)" || exit
 
 discover_op() {
   local op
-  for op in cherry_pick merge rebase revert ; do
-      if [ -f "${gitdir}/${op^^}_HEAD" ]; then
-          echo "${op/_/-}"
-      fi
+  for op in cherry_pick merge rebase revert; do
+    if [ -f "${gitdir}/${op^^}_HEAD" ]; then
+      echo "${op/_/-}"
+    fi
   done
 }
 
@@ -65,12 +65,12 @@ validate_op() {
 }
 
 discover_action() {
-    local action=${1/git-/}
-    if [ "$action" != "abort" ] && [ "$action" != "continue" ]; then
-        echo "Invalid action: $1" >&2
-        exit 1
-    fi
-    echo "$action"
+  local action=${1/git-/}
+  if [ "$action" != "abort" ] && [ "$action" != "continue" ]; then
+    echo "Invalid action: $1" >&2
+    exit 1
+  fi
+  echo "$action"
 }
 
 action=$(discover_action "$(basename "$0")")
diff --git a/home/private_dot_local/bin/executable_git-missing b/home/private_dot_local/bin/executable_git-missing
--- a/home/private_dot_local/bin/executable_git-missing
+++ b/home/private_dot_local/bin/executable_git-missing
@@ -5,27 +5,27 @@ unset -v GREP_OPTIONS
 
 # make a temporary file
 git_extra_mktemp() {
-    mktemp -t "$(basename "$0")".XXXXXXX
+  mktemp -t "$(basename "$0")".XXXXXXX
 }
 
 git_extra_default_branch() {
-    local extras_default_branch init_default_branch
-    extras_default_branch=$(git config --get git-extras.default-branch)
-    init_default_branch=$(git config --get init.defaultBranch)
-    if [ -n "$extras_default_branch" ]; then
-        echo "$extras_default_branch"
-    elif [ -n "$init_default_branch" ]; then
-        echo "$init_default_branch"
-    else
-        echo "main"
-    fi
+  local extras_default_branch init_default_branch
+  extras_default_branch=$(git config --get git-extras.default-branch)
+  init_default_branch=$(git config --get init.defaultBranch)
+  if [ -n "$extras_default_branch" ]; then
+    echo "$extras_default_branch"
+  elif [ -n "$init_default_branch" ]; then
+    echo "$init_default_branch"
+  else
+    echo "main"
+  fi
 }
 #
 # check whether current directory is inside a git repository
 #
 
 is_git_repo() {
-  git rev-parse --show-toplevel > /dev/null 2>&1
+  git rev-parse --show-toplevel >/dev/null 2>&1
   result=$?
   if test $result != 0; then
     >&2 echo 'Not a git repo!'
@@ -36,13 +36,12 @@ is_git_repo() {
 is_git_repo
 
 usage() {
-    echo 1>&2 "usage: git missing [<first branch>] <second branch> [<git log options>] [[--] <path>...]"
+  echo 1>&2 "usage: git missing [<first branch>] <second branch> [<git log options>] [[--] <path>...]"
 }
 
-if [ "${#}" -lt 1 ]
-then
-    usage
-    exit 1
+if [ "${#}" -lt 1 ]; then
+  usage
+  exit 1
 fi
 
 declare -a git_log_args=()
@@ -50,38 +49,36 @@ declare -a branches=()
 declare -a pathspec=()
 declare parse_path=false
 
-for arg in "$@" ; do
+for arg in "$@"; do
 
-    if [[ $parse_path == true ]]; then
-        pathspec+=("$@")
-        break
-    fi
+  if [[ $parse_path == true ]]; then
+    pathspec+=("$@")
+    break
+  fi
 
-    case "$arg" in
-        --)
-            parse_path=true
-            ;;
-        --*)
-            git_log_args+=( "$arg" )
-            ;;
-        *)
-            branches+=( "$arg" )
-            ;;
-    esac
+  case "$arg" in
+  --)
+    parse_path=true
+    ;;
+  --*)
+    git_log_args+=("$arg")
+    ;;
+  *)
+    branches+=("$arg")
+    ;;
+  esac
 done
 
 firstbranch=
 secondbranch=
-if [ ${#branches[@]} -eq 2 ]
-then
-    firstbranch="${branches[0]}"
-    secondbranch="${branches[1]}"
-elif [ ${#branches[@]} -eq 1 ]
-then
-    secondbranch="${branches[0]}"
+if [ ${#branches[@]} -eq 2 ]; then
+  firstbranch="${branches[0]}"
+  secondbranch="${branches[1]}"
+elif [ ${#branches[@]} -eq 1 ]; then
+  secondbranch="${branches[0]}"
 else
-    echo >&2 "error: at least one branch required"
-    exit 1
+  echo >&2 "error: at least one branch required"
+  exit 1
 fi
 
 git log "${git_log_args[@]}" "$firstbranch"..."$secondbranch" --format="%m %h %s" --left-right -- "${pathspec[@]}"
diff --git a/home/private_dot_local/bin/executable_git-skip b/home/private_dot_local/bin/executable_git-skip
--- a/home/private_dot_local/bin/executable_git-skip
+++ b/home/private_dot_local/bin/executable_git-skip
@@ -9,12 +9,14 @@
 #
 # http://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree/13631525#13631525
 
+set -euo pipefile
+
 declare mode root
 
 if (($#)); then
   case "$1" in
-    list | ls) mode=list;;
-    add )) mode=add ;;
+  list | ls) mode=list ;;
+  add) mode=add ;;
   remove | rm) mode=remove ;;
   *)
     echo >&2 "Error: Unknown git-skip subcommand '$1'"
@@ -32,7 +34,11 @@ git-skip-list() {
 }
 
 case "${mode}" in
-  list) git-skip-list ;;
-  add) git update-index --skip-worktree "$@" ;;
-  remove) git update-index --no-skip-worktre "$@" ;;
+list) git-skip-list ;;
+add) git update-index --skip-worktree "$@" ;;
+remove) git update-index --no-skip-worktre "$@" ;;
+*)
+  echo >&2 "Error: Unknown git-skip subcommand '$1'"
+  exit 1
+  ;;
 esac
