Major script formatting cleanup
- Fix git identities script
- Various updates

diff --git a/home/private_dot_local/bin/executable_git-cut-branch b/home/private_dot_local/bin/executable_git-cut-branch
--- a/home/private_dot_local/bin/executable_git-cut-branch
+++ b/home/private_dot_local/bin/executable_git-cut-branch
@@ -1,25 +1,26 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #/ Usage: git-cut-branch <name>
 #/ Create a new branch named <name> pointed at HEAD and reset the current branch
 #/ to the head of its tracking branch. This is useful when working on master and
 #/ you realize you should be on a topic branch.
-set -e
+
+set -eo pipefail
 
 # bail out with message to stderr and exit status 1
 die() {
-    echo "$(basename "$0"):" "$@" 1>&2
-    exit 1
+  echo "$(basename "$0"):" "$@" 1>&2
+  exit 1
 }
 
 # write a short sha for the given sha
 shortsha() {
-    echo "$1" | cut -c1-7
+  echo "$1" | cut -c1-7
 }
 
 # show usage
-[ -z "$1" ] || [ "$1" = "--help" ] && {
-    grep '^#/' "$0" | cut -c4-
-    exit 2
+[[ -z "$1" ]] || [[ "$1" = "--help" ]] && {
+  grep '^#/' "$0" | cut -c4-
+  exit 2
 }
 
 # first argument is the new branch name
@@ -28,38 +29,40 @@ branch="$1"
 # get the current branch for HEAD in refs/heads/<branch> form
 ref=$(git symbolic-ref -q HEAD)
 sha=$(git rev-parse HEAD)
-[ -n "$ref" ] ||
-    die "you're not on a branch"
+[[ -n "${ref}" ]] ||
+  die "you're not on a branch"
 
 # just the branch name please
 current="${ref/refs\/heads\//}"
-[ -n "$current" ] ||
-    die "you're in a weird place; get on a local branch"
+[[ -n "${current}" ]] ||
+  die "you're in a weird place; get on a local branch"
 
 # figure out what branch we're currently tracking
-remote=$(git config --get "branch.$current.remote" || true)
-merge=$(git config --get "branch.$current.merge" | sed 's@refs/heads/@@')
+remote=$(git config --get "branch.${current}.remote" || true)
+merge=$(git config --get "branch.${current}.merge" | sed 's@refs/heads/@@')
 
 # build up a sane <remote>/<branch> name
-if [ -n "$remote" ] && [ -n "$merge" ]; then
-    tracking="$remote/$merge"
-elif [ -n "$merge" ]; then
-    tracking="$merge"
+if [[ -n "${remote}" ]] && [[ -n "${merge}" ]]; then
+  tracking="${remote}/${merge}"
+elif [[ -n "${merge}" ]]; then
+  tracking="${merge}"
 else
-    die "$current is not tracking anything"
+  die "${current} is not tracking anything"
 fi
 
 # make sure there's no changes before we reset hard
 if ! git diff-index --quiet --cached HEAD || ! git diff-files --quiet; then
-    die "cannot cut branch with changes to index or working directory"
+  die "cannot cut branch with changes to index or working directory"
 fi
 
 # reset the current branch to its tracking branch, create the new branch also
 # tracking the original branch, and switch to it.
-git branch "$branch"
-git reset -q --hard "$tracking"
-git checkout -q "$branch"
-git branch --set-upstream "$branch" "$tracking"
-git reset -q --hard "$sha"
-echo "[$(shortsha "$sha")...$(shortsha "$(git rev-parse "$tracking")")] $current"
-echo "[0000000...$(shortsha "$(git rev-parse HEAD)")] $branch"
+git branch "${branch}"
+git reset -q --hard "${tracking}"
+git checkout -q "${branch}"
+git branch --set-upstream "${branch}" "${tracking}"
+git reset -q --hard "${sha}"
+# shellcheck disable=SC2312
+echo "[$(shortsha "${sha}")...$(shortsha "$(git rev-parse "${tracking}")")] ${current}"
+# shellcheck disable=SC2312
+echo "[0000000...$(shortsha "$(git rev-parse HEAD)")] ${branch}"
diff --git a/home/private_dot_local/bin/executable_git-up b/home/private_dot_local/bin/executable_git-up
--- a/home/private_dot_local/bin/executable_git-up
+++ b/home/private_dot_local/bin/executable_git-up
@@ -14,12 +14,12 @@
 
 set -uo pipefail
 
-bn0="$(basename "$0")"
+bn0="$(basename "${0}")"
 readonly bn0
 
 usage() {
   cat <<USAGE
-Usage: $bn0 [options]
+Usage: ${bn0} [options]
 
 An enhanced git-pull that shows a short log of changes immediately after
 merging (git-up) or rebasing (git-reup or git-up --rebase). Submodules are
@@ -76,13 +76,13 @@ halt-error() {
     shift
   fi
 
-  echo >&2 "$bn0: $*"
-  "$call_usage" && usage >&2
+  echo >&2 "${bn0}: $*"
+  "${call_usage}" && usage >&2
   exit 1
 }
 
 git rev-parse --is-inside-work-tree 2>/dev/null 1>/dev/null ||
-  halt-error "$PWD is not a git working tree"
+  halt-error "${PWD} is not a git working tree"
 
 readonly user_re='[^:@]+'
 readonly pass_re='[^@]+'
@@ -91,38 +91,38 @@ readonly port_re='[0-9]+'
 readonly path_re='/([^?#]*)'
 readonly query_re='\?([^#]+)'
 readonly fragment_re='#(.*)'
-readonly auth_re="($user_re)(:($pass_re))?@"
-readonly connection_re="($auth_re)?($host_re)(:($port_re))?"
-readonly url_re="^https://$connection_re($path_re)?($query_re)?($fragment_re)?"
-readonly ssh_re="^ssh://git@([^:]+)(:($port_re))?/(.*)$"
+readonly auth_re="(${user_re})(:(${pass_re}))?@"
+readonly connection_re="(${auth_re})?(${host_re})(:(${port_re}))?"
+readonly url_re="^https://${connection_re}(${path_re})?(${query_re})?(${fragment_re})?"
+readonly ssh_re="^ssh://git@([^:]+)(:(${port_re}))?/(.*)$"
 readonly scp_re="^git@([^:]+):(.*)$"
 
 parse-repo-path() {
-  if [[ "$1" =~ ^([^/]+)/([^/]+)(/.*)?$ ]]; then
+  if [[ "${1}" =~ ^([^/]+)/([^/]+)(/.*)?$ ]]; then
     echo "${BASH_REMATCH[1]}/${BASH_REMATCH[2]/.git/}"
   else
-    echo "invalid repo path: $1"
+    echo >&2 "invalid repo path: ${1}"
     return 1
   fi
 }
 
 get-repo-from-url() {
-  parse-repo-url "$1" repo
+  parse-repo-url "${1}" repo
 }
 
 get-host-from-url() {
-  parse-repo-url "$1" host
+  parse-repo-url "${1}" host
 }
 
 parse-repo-url() {
   local url url_part host repo
-  url="$1"
-  url_part="$2"
+  url="${1}"
+  url_part="${2}"
 
-  if [[ "$url" =~ $url_re ]]; then
+  if [[ "${url}" =~ ${url_re} ]]; then
     if [[ -z "${BASH_REMATCH[5]}" ]] || [[ -z "${BASH_REMATCH[9]}" ]]; then
       # Missing host and/or path
-      echo "invalid URL: $url"
+      echo >&2 "invalid URL: ${url}"
       return 1
     fi
 
@@ -133,12 +133,12 @@ parse-repo-url() {
     fi
 
     if ! repo="$(parse-repo-path "${BASH_REMATCH[9]}")"; then
-      echo "$repo"
+      echo >&2 "${repo}"
       return 1
     fi
-  elif [[ "$url" =~ $ssh_re ]]; then
+  elif [[ "${url}" =~ ${ssh_re} ]]; then
     if [[ -z "${BASH_REMATCH[1]}" ]] || [[ -z "${BASH_REMATCH[4]}" ]]; then
-      echo "invalid URL: $url"
+      echo "invalid URL: ${url}"
       return 1
     fi
 
@@ -147,9 +147,9 @@ parse-repo-url() {
     if ! repo="$(parse-repo-path "${BASH_REMATCH[4]}")"; then
       return 1
     fi
-  elif [[ "$url" =~ $scp_re ]]; then
+  elif [[ "${url}" =~ ${scp_re} ]]; then
     if [[ -z "${BASH_REMATCH[1]}" ]] || [[ -z "${BASH_REMATCH[2]}" ]]; then
-      echo "invalid URL: $url"
+      echo "invalid URL: ${url}"
       return 1
     fi
 
@@ -158,15 +158,15 @@ parse-repo-url() {
       return 1
     fi
   else
-    echo "invalid URL: $url"
+    echo "invalid URL: ${url}"
     return 1
   fi
 
-  case "$url_part" in
-  host) echo "$host" ;;
-  repo) echo "$repo" ;;
+  case "${url_part}" in
+  host) echo "${host}" ;;
+  repo) echo "${repo}" ;;
   *)
-    echo "invalid URL part: $url_part"
+    echo "invalid URL part: ${url_part}"
     return 1
     ;;
   esac
@@ -189,9 +189,10 @@ upstream_host=
 upstream_repo=
 upstream_url=
 
+# shellcheck disable=SC2312
 readarray -t remotes < <(git remote)
 for remote in "${remotes[@]}"; do
-  remote_urls["$remote"]="$(git remote get-url "$remote")"
+  remote_urls["${remote}"]="$(git remote get-url "${remote}")"
 done
 
 merge_upstream=$(git config --get git-up.merge-upstream.enabled)
@@ -206,67 +207,67 @@ if ((${#merge_upstream} == 0)); then
   fi
 fi
 
-if [[ -z "$rebase" ]] && [[ "$bn0" == git-reup ]]; then
+if [[ -z "${rebase}" ]] && [[ "${bn0}" == git-reup ]]; then
   rebase=true
 fi
 
-if [[ -z "$submodule_update" ]]; then
+if [[ -z "${submodule_update}" ]]; then
   submodule_update=true
 fi
 
 while (($#)); do
-  case "$1" in
+  case "${1}" in
   -R | --no-rebase) rebase=false ;;
   -r | --rebase) rebase=true ;;
   -m | --merge-upstream) merge_upstream=true ;;
   -M | --no-merge-upstream) merge_upstream=false ;;
   -s | --submodule-update) submodule_update=true ;;
   -S | --no-submodule-update) submodule_update=false ;;
-  *) args+=("$1") ;;
+  *) args+=("${1}") ;;
   esac
   shift
 done
 
 set -- "${args[@]}"
 
-if "$merge_upstream" && ! which gh >/dev/null 2>/dev/null; then
+if "${merge_upstream}" && ! command -v gh >/dev/null 2>/dev/null; then
   merge_upstream=false
 fi
 
-if "$merge_upstream"; then
+if "${merge_upstream}"; then
   origin=$(git config --get git-up.merge-upstream.origin)
   upstream=$(git config --get git-up.merge-upstream.upstream)
   branch=$(git config --get git-up.merge-upstream.branch)
 
   if ((${#remotes[@]} > 1)); then
     while (($#)); do
-      case "$1" in
+      case "${1}" in
       -o | --origin)
-        if [[ -z "$2" ]]; then
-          halt-error "$1 requires a value"
+        if [[ -z "${2}" ]]; then
+          halt-error "${1} requires a value"
         fi
 
-        origin="$2"
+        origin="${2}"
         shift
         ;;
       -u | --upstream)
-        if [[ -z "$2" ]]; then
-          halt-error "$1 requires a value"
+        if [[ -z "${2}" ]]; then
+          halt-error "${1} requires a value"
         fi
 
-        upstream="$2"
+        upstream="${2}"
         shift
         ;;
       -b | --branch)
-        if [[ -z "$2" ]]; then
-          halt-error "$1 requires a value"
+        if [[ -z "${2}" ]]; then
+          halt-error "${1} requires a value"
         fi
 
-        branch="$2"
+        branch="${2}"
         shift
         ;;
       *)
-        args+=("$1")
+        args+=("${1}")
         ;;
       esac
 
@@ -275,78 +276,78 @@ if "$merge_upstream"; then
 
     set -- "${args[@]}"
 
-    [[ -z "$origin" ]] && origin=origin
+    [[ -z "${origin}" ]] && origin=origin
 
-    if origin_repo="$(get-repo-from-url "$origin")}"; then
-      origin_host="$(get-host-from-url "$origin")"
-      origin_url="$origin"
-    elif origin_repo="$(parse-repo-path "$origin")"; then
+    if origin_repo="$(get-repo-from-url "${origin}")}"; then
+      origin_host="$(get-host-from-url "${origin}")"
+      origin_url="${origin}"
+    elif origin_repo="$(parse-repo-path "${origin}")"; then
       :
     else
-      origin_url="${remote_urls["$origin"]}"
+      origin_url="${remote_urls["${origin}"]}"
 
-      if [[ -z "$origin_url" ]]; then
-        halt-error "origin remote '$origin' does not exist in git repo"
+      if [[ -z "${origin_url}" ]]; then
+        halt-error "origin remote '${origin}' does not exist in git repo"
       fi
 
-      if ! origin_repo="$(get-repo-from-url "$origin_url")"; then
-        halt-error "origin remote: $origin_repo"
+      if ! origin_repo="$(get-repo-from-url "${origin_url}")"; then
+        halt-error "origin remote: ${origin_repo}"
       fi
 
-      origin_host="$(get-host-from-url "$origin_url")"
+      origin_host="$(get-host-from-url "${origin_url}")"
     fi
 
-    if [[ -z "$branch" ]]; then
-      [[ -z "$upstream" ]] && upstream=upstream
+    if [[ -z "${branch}" ]]; then
+      [[ -z "${upstream}" ]] && upstream=upstream
 
-      if upstream_repo="$(get-repo-from-url "$upstream")"; then
-        upstream_host="$(get-host-from-url "$upstream")"
-        upstream_url="$upstream"
-      elif upstream_repo="$(parse-repo-path "$upstream")"; then
+      if upstream_repo="$(get-repo-from-url "${upstream}")"; then
+        upstream_host="$(get-host-from-url "${upstream}")"
+        upstream_url="${upstream}"
+      elif upstream_repo="$(parse-repo-path "${upstream}")"; then
         :
       else
-        upstream_url="${remote_urls["$upstream"]}"
+        upstream_url="${remote_urls["${upstream}"]}"
 
-        if [[ -z "$upstream_url" ]]; then
-          halt-error "upstream remote '$upstream' does not exist in git repo"
+        if [[ -z "${upstream_url}" ]]; then
+          halt-error "upstream remote '${upstream}' does not exist in git repo"
         fi
 
-        if ! upstream_repo="$(get-repo-from-url "$upstream_url")"; then
-          halt-error "upstream remote: $upstream_repo"
+        if ! upstream_repo="$(get-repo-from-url "${upstream_url}")"; then
+          halt-error "upstream remote: ${upstream_repo}"
         fi
 
-        upstream_host="$(get-host-from-url "$upstream_url")"
+        upstream_host="$(get-host-from-url "${upstream_url}")"
       fi
 
       args=()
 
-      if [[ -n "$upstream_host" ]] && [[ "$upstream_host" != github.com ]]; then
-        args=(--hostname "$upstream_host")
+      if [[ -n "${upstream_host}" ]] && [[ "${upstream_host}" != github.com ]]; then
+        args=(--hostname "${upstream_host}")
       fi
 
       # Get the default branch from the upstream
-      if ! branch="$(gh "${args[@]}" api repos/"$upstream_repo" --template '{{ .default_branch }}')"; then
-        halt-error "could not get default branch from $upstream_repo"
+      if ! branch="$(gh "${args[@]}" api repos/"${upstream_repo}" --template '{{ .default_branch }}')"; then
+        halt-error "could not get default branch from ${upstream_repo}"
       fi
 
-      if [[ -z "$branch" ]]; then
-        halt-error "could not get default branch from $upstream_repo"
+      if [[ -z "${branch}" ]]; then
+        halt-error "could not get default branch from ${upstream_repo}"
       fi
     fi
 
     args=()
 
-    if [[ -n "$origin_host" ]] && [[ "$origin_host" != github.com ]]; then
-      args=(--hostname "$origin_host")
+    if [[ -n "${origin_host}" ]] && [[ "${origin_host}" != github.com ]]; then
+      args=(--hostname "${origin_host}")
     fi
 
-    if result="$(gh "${args[@]}" api repos/"$origin_repo"/merge-upstream -F branch="$branch")"; then
+    if _result="$(gh "${args[@]}" api repos/"${origin_repo}"/merge-upstream -F branch="${branch}")"; then
       echo "${origin_repo} branch ${branch} merged with ${upstream_repo}"
     else
-      echo 2>&1 "$bn0: Error updating upstream branch."
+      echo 2>&1 "${bn0}: Error updating upstream branch."
     fi
   else
-    echo 2>&1 "$bn0: Upstream merge enabled but there is only one remote. Skipped."
+    echo 2>&1 "${bn0}: Upstream merge enabled but there is only one remote. Skipped."
   fi
 fi
 
@@ -362,31 +363,31 @@ else
 fi
 
 # when invoked as git-reup, run as `git pull --rebase'
-"$rebase" && pull_args=(--rebase "${pull_args[@]}")
+"${rebase}" && pull_args=(--rebase "${pull_args[@]}")
 
 git pull "${pull_args[@]}"
 echo
 
 # show diffstat of all changes if we're pulling with --rebase. not
 # sure why git-pull only does this when merging.
-"$rebase" && {
+"${rebase}" && {
   declare diff
-  diff=$(git --no-pager diff --color --stat HEAD@{1}.. | sed 's/^/ /')
+  diff=$(git --no-pager diff --color --stat "HEAD@{1}.." | sed 's/^/ /')
 
-  [[ -z "$diff" ]] || printf "Diff:\n%s\n\n" "$diff"
+  [[ -z "${diff}" ]] || printf "Diff:\n%s\n\n" "${diff}"
 }
 
 # show an abbreviated commit log of stuff that was just merged.
 {
   declare log
-  log=$(git log --color --pretty=oneline --abbrev-commit HEAD@{1}.. | sed 's/^/  /')
-  [[ -z "$log" ]] || printf "Log:\n%s\n\n" "$log"
+  log=$(git log --color --pretty=oneline --abbrev-commit "HEAD@{1}.." | sed 's/^/  /')
+  [[ -z "${log}" ]] || printf "Log:\n%s\n\n" "${log}"
 }
 
 echo "Branches:"
 git branch -vv
 
-"$submodule_update" && {
+"${submodule_update}" && {
   # Update any submodules
   git submodule --quiet update --init --recursive
 }
diff --git a/home/private_dot_local/bin/executable_it2ul b/home/private_dot_local/bin/executable_it2ul
--- a/home/private_dot_local/bin/executable_it2ul
+++ b/home/private_dot_local/bin/executable_it2ul
@@ -1,57 +1,62 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+set -eo pipefail
 
 trap clean_up EXIT
-_STTY=$(stty -g) ## Save current terminal setup
-stty -echo       ## Turn off echo
+_STTY="$(stty -g)" ## Save current terminal setup
+stty -echo         ## Turn off echo
 
-function clean_up() {
-  stty "$_STTY" ## Restore terminal settings
+clean_up() {
+  stty "${_STTY}" ## Restore terminal settings
 }
 
-function show_help() {
-  echo "Usage: $(basename $0) [destination [tar flags]]" 1>&2
-  echo "  If given, the destination specifies the directory to place downloaded files."
-  echo "  Further options are passed through to tar. See your system's manpage for tar for details."
+show_help() {
+  cat >&2 <<HELP
+Usage: $(basename "$0") [destination [tar flags]]
+
+If given, the destination specifies the directory to place downloaded
+files. Further options are passed through to tar. See your system's manpage
+for tar for details.
+HELP
 }
 
-function bad_input() {
-  echo "Bad input: %1" 1>&2
+bad_input() {
+  echo >&2 "Bad input: $1"
   exit 1
 }
 
-function die() {
-  echo "Fatal error: $1" 1>&2
+die() {
+  echo >&2 "Fatal error: $1"
   exit 1
 }
 
-function read_base64_stanza() {
-  value=""
-  while read line; do
-    if [ "$line" == "" ]; then
+read_base64_stanza() {
+  while read -r line; do
+    if [[ "${line}" == "" ]]; then
       break
     fi
-    printf "%s" "$line"
+    printf "%s" "${line}"
   done
 }
 
-function decode() {
+decode() {
   VERSION=$(base64 --version 2>&1)
-  if [[ "$VERSION" =~ fourmilab ]]; then
+  if [[ "${VERSION}" =~ fourmilab ]]; then
     BASE64ARG=-d
-  elif [[ "$VERSION" =~ GNU ]]; then
+  elif [[ "${VERSION}" =~ GNU ]]; then
     BASE64ARG=-di
   else
     BASE64ARG=-D
   fi
 
-  base64 "$BASE64ARG" <<<"$1"
+  base64 "${BASE64ARG}" <<<"$1"
 }
 
 # tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
 # <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
 # only accepts ESC backslash for ST.
-function print_osc() {
-  if [[ $TERM == screen* ]]; then
+print_osc() {
+  if [[ "${TERM}" == screen* ]]; then
     printf "\033Ptmux;\033\033]"
   else
     printf "\033]"
@@ -59,35 +64,35 @@ function print_osc() {
 }
 
 # More of the tmux workaround described above.
-function print_st() {
-  if [[ $TERM == screen* ]]; then
+print_st() {
+  if [[ "${TERM}" == screen* ]]; then
     printf "\a\033\\"
   else
     printf "\a"
   fi
 }
 
-function send_request_for_upload() {
+send_request_for_upload() {
   print_osc
-  printf '1337;RequestUpload=format=tgz' ""
+  printf '1337;RequestUpload=format=tgz'
   print_st
 }
 
-location="$PWD"
-if [[ $# > 0 ]]; then
+location="$(PWD)"
+if (($#)); then
   location="$1"
   shift
 fi
 
 send_request_for_upload
-read status
+read -r status
 
-if [[ $status == ok ]]; then
-  data=$(read_base64_stanza)
+if [[ "${status}" == ok ]]; then
+  data="$(read_base64_stanza)"
   clean_up
-  decode "$data" | tar -x -z -C "$location" -f - $* 1>&2
-elif [[ $status == abort ]]; then
-  echo "Upload aborted" 1>&2
+  decode "${data}" | tar -x -z -C "${location}" -f - "$@" >&2
+elif [[ "${status}" == abort ]]; then
+  echo >&2 "Upload aborted"
 else
-  die "Unknown status: $status" 1>&2
+  die >&2 "Unknown status: ${status}"
 fi
diff --git a/home/private_dot_local/bin/executable_macports b/home/private_dot_local/bin/executable_macports
--- a/home/private_dot_local/bin/executable_macports
+++ b/home/private_dot_local/bin/executable_macports
@@ -9,14 +9,14 @@ tested-on() {
   hardware="$(uname -m)"
 
   if build_tools="$(xcodebuild -version 2>/dev/null)"; then
-    build_tools="$(echo "$build_tools" | awk 'NR==1 { x=$0 } END { print x" "$NF }')"
+    build_tools="$(echo "${build_tools}" | awk 'NR==1 { x=$0 } END { print x" "$NF }')"
   elif build_tools="$(pkgutil --pkg-info=com.apple.pkg.CLTools_Executables)"; then
-    build_tools="$(echo "$build_tools" | awk '/version:/ { print $2 }')"
-    build_tools="Command Line Tools $build_tools"
+    build_tools="$(echo "${build_tools}" | awk '/version:/ { print $2 }')"
+    build_tools="Command Line Tools ${build_tools}"
   fi
 
-  echo macOS "$product_version" "$build_version" "$hardware"
-  echo "$build_tools"
+  echo macOS "${product_version}" "${build_version}" "${hardware}"
+  echo "${build_tools}"
 }
 
 set-port-version() {
@@ -27,7 +27,7 @@ set-port-version() {
   read -r version <"${port[clip]}.version"
   port[version]="${version}"
 
-  if [[ "${port[golang]:-}" ]]; then
+  if [[ -n "${port[golang]:-}" ]]; then
     local repo version prefix
     awk '/^go.setup/ { print $2, $3, $4; }' "${port[clip]}" >"${port[clip]}.version"
     read -r repo version prefix <"${port[clip]}.version"
@@ -36,7 +36,7 @@ set-port-version() {
     port[tag_url]="https://raw.githubusercontent.com/${repo/github.com\//}/refs/tags/${prefix:-}${version}"
   fi
 
-  if [[ "${port[github]:-}" ]]; then
+  if [[ -n "${port[github]:-}" ]]; then
     local owner name version prefix
     awk '/^github.setup/ { print $2, $3, $4, $5; }' "${port[clip]}" >"${port[clip]}.version"
     read -r owner name version prefix <"${port[clip]}.version"
@@ -66,8 +66,8 @@ test-port-passage() {
   local id created tmp
   created=false
   tmp="$(mktemp)"
-  rm -f "$tmp"
-  id="$(basename "$tmp")"
+  rm -f "${tmp}"
+  id="$(basename "${tmp}")"
 
   if ! [[ -f ~/.passage/identities ]]; then
     mkdir -p ~/.passage
@@ -77,11 +77,11 @@ test-port-passage() {
 
   (
     set -x
-    passage generate test."$id"
-    passage rm -f test."$id"
+    passage generate test."${id}"
+    passage rm -f test."${id}"
   )
 
-  "$created" && rm -rf ~/.passage
+  "${created}" && rm -rf ~/.passage
 }
 
 update-port() {
@@ -182,20 +182,20 @@ update-port() {
     port_test=(rebels --version)
     ;;
   *)
-    echo >&2 "$fn: port $1: No update procedure"
+    echo >&2 "${fn}: port $1: No update procedure"
     return 1
     ;;
   esac
 
   if "${port[unstable]:-false}" && ! [[ "${2:-}" == --force ]]; then
-    echo >&2 "$fn: $1 cannot be updated automatically because of Cargo.lock instability"
+    echo >&2 "${fn}: $1 cannot be updated automatically because of Cargo.lock instability"
     return 1
   fi
 
   if "${port[public]:-false}"; then
     port[root]="$(zoxide query macports-ports)"
   else
-    port[root]="$HOME/ports"
+    port[root]="${HOME}/ports"
   fi
 
   port[name]="$1"
@@ -216,18 +216,19 @@ update-port() {
   set-port-version
 
   if [[ -z "${port[version]:-}" ]]; then
-    echo >&2 "$fn: port ${port[name]} cannot determine next target version"
+    echo >&2 "${fn}: port ${port[name]} cannot determine next target version"
     return 1
   fi
 
   if git log --grep="\\b${port[name]}.\\+${port[version]}" --since "7 days ago" | grep -q .; then
-    echo >&2 "$fn: port ${port[name]}: ${port[version]} has already been merged"
+    echo >&2 "${fn}: port ${port[name]}: ${port[version]} has already been merged"
     git log --grep="\\b${port[name]}.\\+${port[version]}" --since "7 days ago" >&2
     return 1
   fi
 
-  if [[ "$(gh pr list --search "${port[name]}" -q '(. | length) > 0' --json number)" == true ]]; then
-    echo >&2 "$fn: port ${port[name]}: ${port[version]} already has an open PR"
+  if prs="$(gh pr list --search "${port[name]} in:title" -q '(. | length) > 0' --json number)" &&
+    [[ "${prs}" == true ]]; then
+    echo >&2 "${fn}: port ${port[name]}: ${port[version]} already has an open PR"
     gh pr list --search ruby-build -q 'map("#\(.number) \(.title)") | .[]' --json number,title >&2
     return 1
   fi
@@ -238,10 +239,10 @@ update-port() {
     git switch --create "${port[name]}-${port[version]}" "${branch}"
   fi
 
-  if [[ "${port[needs_crates]:-}" ]]; then
+  if [[ -n "${port[needs_crates]:-}" ]]; then
     sed '/^cargo.crates/,$d' "${port[clip]}" >"${port[file]}"
 
-    if [[ "${port[cargo_lock]:-crates}" == github ]] && [[ "${port[tag_url]:-}" ]]; then
+    if [[ "${port[cargo_lock]:-crates}" == github ]] && [[ -n "${port[tag_url]:-}" ]]; then
       curl -sSL "${port[tag_url]}/Cargo.lock" -o "${port[clip]}.Cargo.lock"
       crate2port "${port[clip]}.Cargo.lock" >>"${port[file]}"
     else
@@ -268,7 +269,7 @@ update-port() {
 
   if "${port[public]}"; then
     if ! [[ -s "${port[pr]}" ]]; then
-      echo >&2 "$fn: port ${port[name]}: Error generating pull request body"
+      echo >&2 "${fn}: port ${port[name]}: Error generating pull request body"
       return 1
     fi
 
@@ -305,14 +306,14 @@ prepare-pr() (
   description="$(git log "${branch:-master}".. --format=%B)"
   tested_on="$(tested-on)"
 
-  cat >"$pr_file" <<INFO
+  cat >"${pr_file}" <<INFO
 #### Description
 
-$description
+${description}
 
 ##### Tested on
 
-$tested_on
+${tested_on}
 
 ##### Verification
 
@@ -326,15 +327,15 @@ Have you
 - [x] tested basic functionality of all binary files?
 INFO
 
-  cat "$pr_file"
+  cat "${pr_file}"
 )
 
 trac-get() {
   local url="$1" dir="$2"
 
-  [[ -n "$dir" ]] || dir=.
+  [[ -n "${dir}" ]] || dir=.
 
-  curl "$url?format=raw" --create-dirs -o "$dir/$(basename "$1")"
+  curl "${url}?format=raw" --create-dirs -o "${dir}/$(basename "$1")"
 }
 
 trac-patch() {
@@ -343,15 +344,15 @@ trac-patch() {
   while [[ "$1" == -* ]]; do
     [[ "$1" == -- ]] && break
 
-    cmd="$cmd $1"
+    cmd="${cmd} $1"
     shift
   done
 
-  [[ -n "$cmd" ]] || cmd="--strip 0"
+  [[ -n "${cmd}" ]] || cmd="--strip 0"
 
   trac-get "$@"
 
-  patch "$cmd" <"$(basename "$1")"
+  patch "${cmd}" <"$(basename "$1")"
 }
 
 update() {
