Apply changes made locally

diff --git a/private_dot_direnvrc b/private_dot_direnvrc
--- a/private_dot_direnvrc
+++ b/private_dot_direnvrc
@@ -116,9 +116,19 @@ use_kx() {
   [[ "${version}" == --auto ]] && version="$(read_version_file .elixir-version)"
   [[ -z "${version}" ]] && return
 
+  local matching_version
+  matching_version="$(
+    kx list installed | awk "/${version}/ { print \$1 }" | sort -ru | head -1
+  )"
+
+  if [[ -z "${matching_version}" ]]; then
+    echo "Error: Missing elixir version: $version. Install using kx." 1>&2
+    return 1
+  fi
+
   local activate
   # direnv _always_ works with bash
-  activate="$(USERSHELL=bash kx source ${version})" || {
+  activate="$(USERSHELL=bash kx source ${matching_version})" || {
     echo >&2 "Error: Missing elixir version: $version. Install using kx."
     return 1
   }
